2021-03-15 15:52:13,673 ERROR: Exception on /auth/unconfirmed [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 75, in unconfirmed
    return render_template('auth/unconfirmed.html')
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/weiqidu/project/website_new/app/templates/auth/unconfirmed.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/weiqidu/project/website_new/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/weiqidu/project/website_new/app/templates/base.html", line 77, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/weiqidu/project/website_new/app/templates/auth/unconfirmed.html", line 5, in block "app_content"
    <h1>{{ _('你好') }}: {{ user.username }}</h1>
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2021-03-15 15:53:43,334 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 15:56:00,073 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 15:56:59,418 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 16:05:25,189 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 16:05:37,056 ERROR: Exception on /auth/unconfirmed [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 75, in unconfirmed
    return render_template('auth/unconfirmed.html')
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/weiqidu/project/website_new/app/templates/auth/unconfirmed.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/weiqidu/project/website_new/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/weiqidu/project/website_new/app/templates/base.html", line 77, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/weiqidu/project/website_new/app/templates/auth/unconfirmed.html", line 10, in block "app_content"
    <h5><a href="{{ url_for('auth.confirm') }}">{{ _('点击这里重新发送!') }}</a></h5>
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.confirm'. Did you forget to specify values ['token']?
2021-03-15 16:07:25,197 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 16:07:39,184 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 81, in resend_confirmation
    send_email(current_user.email, '激活你的账户', 'auth/email/confirm', user=current_user, token=token)
NameError: name 'send_email' is not defined
2021-03-15 16:07:58,184 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
