2021-03-15 17:01:10,321 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 82, in resend_confirmation
    send_email(current_user.email, '激活你的账户', 'auth/email/confirm', user=current_user, token=token)
  File "/Users/weiqidu/project/website_new/app/email.py", line 22, in send_email
    msg.html = render_template('email/'+template+'.html', **kwargs)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/auth/email/confirm.html
2021-03-15 17:19:39,460 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 17:22:40,387 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 17:22:43,691 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 82, in resend_confirmation
    send_email(current_user.email, '激活你的账户', 'auth/email/confirm', user=current_user, token=token)
  File "/Users/weiqidu/project/website_new/app/email.py", line 22, in send_email
    msg.html = render_template('email/'+template+'.html', **kwargs)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/auth/email/confirm.html
2021-03-15 17:35:13,933 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 17:35:17,022 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 82, in resend_confirmation
    send_email(current_user.email, '激活你的账户', 'auth/email/confirm', user=current_user, token=token)
TypeError: send_email() got an unexpected keyword argument 'user'
2021-03-15 17:35:47,207 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 17:36:01,891 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 82, in resend_confirmation
    send_email(current_user.email, '激活你的账户', 'auth/email/confirm', user=current_user, token=token)
TypeError: send_email() got an unexpected keyword argument 'user'
2021-03-15 17:38:00,960 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
